version: '3'
services:
  service:
    build: app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - theatre-db
    volumes:
      - ./static:/opt/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./static:/data:ro
    depends_on:
      - service
    ports:
      - "80:80"

  theatre-db:
    image: postgres:16
    restart: always
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql